sudo: false
dist: xenial

language: python

python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - python setup.py --quiet install

script:
    - python test_eradicate.py

after_success:
    - travis_retry pip --quiet install coverage

    - coverage run --include='eradicate.py,test_eradicate.py' test_eradicate.py
    - coverage report --show-missing

    - travis_retry pip install --quiet coveralls
    - coveralls
