---
name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests with python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.7", "3.8", "3.9", "3.10", "pypy-2.7", "pypy-3.7", "pypy-3.8"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project and deps
        run: |
          python setup.py install
          pip install "mock; python_version>='2.7' and python_version<'2.8'"

      - name: Run tests
        run: python test_eradicate.py


  coverage:
    name: Run tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3

      - name: Install project and deps
        run: |
          python setup.py install
          pip install "mock; python_version>='2.7' and python_version<'2.8'"
          pip install coverage

      - name: Run test with coverage
        run: |
          coverage run --include='eradicate.py,test_eradicate.py' test_eradicate.py
          coverage report --show-missing
