---
name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    name: Tests with python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "pypy-2.7", "pypy-3.7", "pypy-3.8"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print full Python version
        id: print-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print(sys.version_info)")

      - name: Install project
        run: python setup.py install

      - name: Install mock
        run: pip install "mock; python_version>='2.7' and python_version<'2.8'"

      - name: Run test file
        run: python test_eradicate.py


  coverage:
    name: Run tests with coverage
    needs: [tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2

      - name: Print full Python version
        id: print-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print(sys.version_info)")

      - name: Install project
        run: python setup.py install

      - name: Install mock
        run: pip install "mock; python_version>='2.7' and python_version<'2.8'"

      - name: Install coverage
        run: pip install coverage

      - name: Run test with coverage
        run: coverage run --include='eradicate.py,test_eradicate.py' test_eradicate.py

      - name: Report coverage result
        run: coverage report --show-missing

      - name: Install coveralls
        run: pip install coveralls

      - name: Report coverage to coveralls
        run: coveralls
